accounts:
  - name: alice
    coins: ["10000000mand"]
  - name: bob
    coins: ["10000000mand"]
  - name: carrot
    coins: ["9000000mand"]
  - name: frooti
    coins: ["7000000mand"]
  - name: lemon
    coins: ["9000000mand"]
  - name: melon
    coins: ["8000000mand"]
  - name: potato
    coins: ["3000000mand", "10000000cred"]
  - name: mandfaucet
    coins: ["1000000000000mand"]

validator:
  name: potato
  staked: "10000000cred"

client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

genesis:
  app_state:
    staking:
      params:
        bond_denom: "cred"
        unbonding_time: "0.001s"
    gov:
      deposit_params:
        min_deposit: [{ "amount": "10000000", "denom": "cred" }]
    mint:
      params:
        mint_denom: "mand"
    crisis:
      constant_fee:
        denom: "mand"
    bank:
      params:
        send_enabled: [{"denom": "cred","enabled": false}]
