accounts:
  - name: alice
    coins: ["10000000mand", "200000000cred"]
  - name: bob
    coins: ["10000000mand", "100000000cred"]
  - name: potato
    coins: ["3000000mand", "10000000cred"]
  - name: carrot
    coins: ["9000000mand", "30000000cred"]
  - name: pumpkin
    coins: ["7000000mand", "50000000cred"]

validator:
  name: potato
  staked: "9000000cred"

client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

faucet:
  name: bob
  coins: ["1000000mand", "10000000cred"]

genesis:
  app_state:
    staking:
      params:
        bond_denom: "cred"
        unbonding_time: "0.001s"
    mint:
      params:
        mint_denom: "cred"
    bank:
      params:
        send_enabled: [{"denom": "cred","enabled": false}]
